---
# Source: ozwdaemon/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozwdaemon
  labels:
    helm.sh/chart: ozwdaemon-0.1.3
    app.kubernetes.io/name: ozwdaemon
    app.kubernetes.io/instance: ozwdaemon
    app.kubernetes.io/version: "amd64-173"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate

    rollingUpdate: null
  selector:
    matchLabels:
      app.kubernetes.io/name: ozwdaemon
      app.kubernetes.io/instance: ozwdaemon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ozwdaemon
        app.kubernetes.io/instance: ozwdaemon
      annotations:
        seccomp.security.alpha.kubernetes.io/defaultProfileName: unconfined
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: ozwdaemon
          securityContext:
            privileged: true
          image: "openzwave/ozwdaemon:allinone-arm64-180"
          imagePullPolicy: IfNotPresent
#          command: 
#            - "/bin/sh"
#            - "-c"
#            - "/usr/local/bin/ozwdaemon -s /dev/ttyUSB0 --mqtt-server mosquitto"
          ports:
            - name: http
              containerPort: 1982
              protocol: TCP
          env:
            - { name: "USB_PATH", value: "/dev/ttyUSB0" }
            - { name: "MQTT_SERVER", value: "mosquitto" }
            - { name: "OZW_NETWORK_KEY", value: "TODO: ADD YOUR KEY" }
          volumeMounts:
            - name: data
              mountPath: /opt/ozw/config
            - name: device
              mountPath: /dev/ttyUSB0
          resources:
            limits:
              cpu: 1500m
              memory: 1500Mi
            requests:
              cpu: 250m
              memory: 250Mi
      volumes:
        - name: device
          hostPath:
            path: "/dev/ttyACM0"
        - name: data
          persistentVolumeClaim:
            claimName: ozwdaemon
      nodeSelector:
        device: zwave
