persistence:
  data:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
    # existingClaim: "data-mosquitto-0"

resources:
  requests:
    cpu: "50m"
    memory: "100Mi"
  limits:
    cpu: "200m"
    memory: "500Mi"
