{
 "title": "Home Assistant",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "sum by(friendly_name) (temperature_c{friendly_name!~\"Living Room Thermostat|Upstairs Thermostat|Subaru Crosstrek External Temp\"})",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "sum by(friendly_name) (humidity_percent)",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Lights",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(friendly_name) (light_state)",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "sum by(friendly_name) (switch_state{friendly_name=~\"Roof Lights|Salt Lamp\"}) * 100",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(friendly_name) (sensor_unit_percent{friendly_name=~\".*Illuminance\"})",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Presence",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(friendly_name) (person_state)",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "TV Usage",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(friendly_name) (binary_sensor_state{friendly_name=~\".*tv\"})",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Last Motion",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(friendly_name) (last_updated_time_seconds{friendly_name=~\".*Motion.*\"})",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}