{
 "title": "Spot Look Back",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Artists",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select unnest(artist_names) as artist, count(*) as count from tracks group by 1 order by 2 desc limit 10;"
    }
   ]
  },
  {
   "title": "Top Songs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select track_name, array_to_string(artist_names, ', '), count(*) from tracks group by 1,2 order by 3 desc limit 10;"
    }
   ]
  },
  {
   "title": "Top Artists Past Week",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select unnest(artist_names) as artist, count(*) as count from tracks where played_at > current_date - interval '7 days' group by 1 order by 2 desc limit 10;"
    }
   ]
  },
  {
   "title": "Top Songs Past Week",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "select track_name, array_to_string(artist_names, ', ') as artists, count(*) as play_count from tracks where played_at > current_date - interval '7 days' group by 1,2 order by 3 desc limit 10;"
    }
   ]
  }
 ]
}