serviceTCP:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "192.168.78.15"
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceUDP:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: "192.168.78.15"
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

resources:
  requests:
    cpu: "250m"
    memory: "150Mi"
  limits:
    cpu: "1000m"
    memory: "500Mi"

persistentVolumeClaim:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: "500Mi"
