apiVersion: v1
kind: Endpoints
metadata:
  name: pivpn
  namespace: pivpn
  labels:
    app.kubernetes.io/name: pivpn
    release: kube-prometheus-stack
subsets:
  - addresses:
    - ip: 192.168.78.9
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
