apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pivpn
  namespace: pivpn
  labels:
    app.kubernetes.io/name: pivpn
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pivpn
  namespaceSelector:
    matchNames:
      - pivpn
  endpoints:
    - port: metrics
