apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: pushover
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  receivers:
  - name: pushover
    pushoverConfigs:
    - userKey:
        name: pushover
        key: userKey
      token:
        name: pushover
        key: token
  route:
    receiver: pushover
    groupBy:
    - job
    groupWait: 30s
    repeatInterval: 12h
    matchers:
    - name: alertname
      value: NetworkClosetTemperature
