defaultRules:
  create: true
  rules:
    etcd: false
    kubeScheduler: false

global:
  rbac:
    pspEnabled: false

alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.home
    paths:
      - /
    pathType: ImplementationSpecific
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi

grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    hosts:
      - grafana.home
    path: /
  plugins:
    - natel-discrete-panel
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
    storageClassName: longhorn
    accessModes: ["ReadWriteOnce"]

  additionalDataSources:
    - name: PostgreSQL - Spot Look Back
      type: postgres
      url: # db url:port
      database: spot-look-back
      user: grafana
      jsonData:
        sslmode: require
        postgresVersion: 1000
        tlsSkipVerify: true
        tlsConfigurationMethod: file-content
      secureJsonData:
        password: # password
        tlsCACert: |
          -----BEGIN CERTIFICATE-----
          -----END CERTIFICATE-----

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kube-state-metrics:
  podSecurityPolicy:
    enabled: false

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 1000m
      memory: 500Mi

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.home
    paths:
      - /
    pathType: ImplementationSpecific
  prometheusSpec:
    serviceMonitorNamespaceSelector:
      matchLabels:
        prometheus: scrape
    retention: 10d
    retentionSize: 12GB
    resources:
      requests:
        cpu: 600m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 15Gi
