alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 50Mi 
      limits:
        cpu: 1000m
        memory: 500Mi

grafana:
  plugins:
  - natel-discrete-panel
  adminPassword: prom-operator
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
    storageClassName: longhorn
    accessModes: ["ReadWriteOnce"]
  ingress:
    enabled: true
    hosts:
      - grafana.home
    path: /
    tls: []

kubeControllerManager:
  enabled: false

coreDns:
  enabled: true

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 1000m
      memory: 500Mi

prometheus:
  enabled: true
  ingress:
    enabled: false
    hosts:
      - prometheus.home
    paths:
      - /
  prometheusSpec:
    retention: 10d
    retentionSize: 12GB
    serviceMonitorNamespaceSelector:
      matchLabels:
        prometheus: scrape
    resources:
      requests:
        cpu: 600m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 15Gi
