apiVersion: v1
kind: ConfigMap
metadata:
  name: hass-configuration
  namespace: home-assistant
data:
  configuration.yaml: |
    # Configure a default setup of Home Assistant (frontend, api, etc)
    default_config:

    # Text to speech
    tts:
      - platform: google_translate

    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    light:
      - platform: group
        name: Office Lights
        entities:
          - light.office_back_left_light
          - light.office_back_right_light
          - light.office_front_left_light
          - light.office_front_right_light
      - platform: group
        name: Key Lights
        entities:
          - light.key_light_left
          - light.key_light_right

    prometheus:

    nest:
      client_id: !secret nest_client_id
      client_secret: !secret nest_client_secret
      project_id: !secret nest_project_id
      subscriber_id: !secret nest_subscriber_id

    logbook:

    sensor:
      - platform: template
        sensors:
          outside_temperature:
            friendly_name: Outside Temperature
            unit_of_measurement: °F
            value_template: "{{ state_attr('weather.climacell_nowcast', 'temperature') }}"
            device_class: temperature
