apiVersion: apps/v1
kind: Deployment
metadata:
  name: hass
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: hass
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: hass
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: hass
    spec:
      nodeSelector:
        device: zwave
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: hass
          image: "homeassistant/home-assistant:2020.12.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          volumeMounts:
          - mountPath: /config
            name: config
          # - mountPath: /dev/ttyACM0
            # name: zwave
          # securityContext:
            # runAsUser: 0
            # privileged: true
            # allowPrivilegeEscalation: true
          resources:
            requests:
              cpu: "1000m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "3Gi"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: hass-config
      # - name: zwave
        # hostPath:
            # path: /dev/ttyACM0
