apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwavejs2mqtt
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: zwavejs2mqtt
    app.kubernetes.io/instance: zwavejs2mqtt
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: zwavejs2mqtt
      app.kubernetes.io/instance: zwavejs2mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zwavejs2mqtt
        app.kubernetes.io/instance: zwavejs2mqtt
    spec:
      nodeSelector:
        device: zwave
      containers:
        - name: zwavejs2mqtt
          image: zwavejs/zwavejs2mqtt:1.0.3
          livenessProbe:
            failureThreshold: 12
            httpGet:
              httpHeaders:
                - name: Accept
                  value: text/plain
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          ports:
            - containerPort: 8091
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 1500m
              memory: 750Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /dev/ttyUSB1
              name: zwavestick
            - mountPath: /usr/src/app/store
              name: data
      volumes:
        - name: zwavestick
          hostPath:
            path: /dev/ttyACM0
        - name: data
          persistentVolumeClaim:
            claimName: zwavejs2mqtt
        # - name: config <-- if putting your settings.json in a secret
        #   secret:
        #     defaultMode: 420
        #     secretName: zwavejs2mqtt
