apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwavejs2mqtt
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: zwavejs2mqtt
    app.kubernetes.io/instance: zwavejs2mqtt
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: longhorn
