apiVersion: v1
kind: Service
metadata:
  name: zwavejs2mqtt
  namespace: home-assistant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: zwavejs2mqtt
