apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dodyndns
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - --domain
            - doesnotscale.com
            - --record
            - home
            - --token
            - $(TOKEN)
            env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: dodyndns
            image: eddiezane/dodyndns:latest
            # TODO: Update this for docker hub changes
            imagePullPolicy: Always
            name: dodyndns
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
