apiVersion: batch/v1
kind: CronJob
metadata:
  name: cfddns
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - --domain
            - doesnotscale.com
            - --record
            - home
            - --token
            - $(TOKEN)
            env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: cfddns
            image: eddiezane/cfddns:v0.1.1
            imagePullPolicy: IfNotPresent
            name: cfddns
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
